version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8081:80/tcp"
    environment:
      TZ: 'Europe/Moscow'
      WEBPASSWORD: 'very_secret'
    volumes:
      - '${PWD}/config:/etc/pihole/'
      - '${PWD}/dnsmasq:/etc/dnsmasq.d/'
    restart: unless-stopped
